# This file has been generated by node2nix 1.11.1. Do not edit!

{
  nodeEnv,
  fetchurl,
  fetchgit,
  nix-gitignore,
  stdenv,
  lib,
  globalBuildInputs ? [ ],
}:

let
  sources = {
    "@isaacs/cliui-8.0.2" = {
      name = "_at_isaacs_slash_cliui";
      packageName = "@isaacs/cliui";
      version = "8.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@isaacs/cliui/-/cliui-8.0.2.tgz";
        sha512 = "O8jcjabXaleOG9DQ0+ARXWZBTfnP4WNAqzuiJK7ll44AmxGKv/J2M4TPjxjY3znBCfvBXFzucm1twdyFybFqEA==";
      };
    };
    "@jridgewell/gen-mapping-0.3.8" = {
      name = "_at_jridgewell_slash_gen-mapping";
      packageName = "@jridgewell/gen-mapping";
      version = "0.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/gen-mapping/-/gen-mapping-0.3.8.tgz";
        sha512 = "imAbBGkb+ebQyxKgzv5Hu2nmROxoDOXHh80evxdoXNOrvAnVx7zimzc1Oo5h9RlfV4vPXaE2iM5pOFbvOCClWA==";
      };
    };
    "@jridgewell/resolve-uri-3.1.2" = {
      name = "_at_jridgewell_slash_resolve-uri";
      packageName = "@jridgewell/resolve-uri";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/resolve-uri/-/resolve-uri-3.1.2.tgz";
        sha512 = "bRISgCIjP20/tbWSPWMEi54QVPRZExkuD9lJL+UIxUKtwVJA8wW1Trb1jMs1RFXo1CBTNZ/5hpC9QvmKWdopKw==";
      };
    };
    "@jridgewell/set-array-1.2.1" = {
      name = "_at_jridgewell_slash_set-array";
      packageName = "@jridgewell/set-array";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/set-array/-/set-array-1.2.1.tgz";
        sha512 = "R8gLRTZeyp03ymzP/6Lil/28tGeGEzhx1q2k703KGWRAI1VdvPIXdG70VJc2pAMw3NA6JKL5hhFu1sJX0Mnn/A==";
      };
    };
    "@jridgewell/sourcemap-codec-1.5.0" = {
      name = "_at_jridgewell_slash_sourcemap-codec";
      packageName = "@jridgewell/sourcemap-codec";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/sourcemap-codec/-/sourcemap-codec-1.5.0.tgz";
        sha512 = "gv3ZRaISU3fjPAgNsriBRqGWQL6quFx04YMPW/zD8XMLsU32mhCCbfbO6KZFLjvYpCZ8zyDEgqsgf+PwPaM7GQ==";
      };
    };
    "@jridgewell/trace-mapping-0.3.25" = {
      name = "_at_jridgewell_slash_trace-mapping";
      packageName = "@jridgewell/trace-mapping";
      version = "0.3.25";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/trace-mapping/-/trace-mapping-0.3.25.tgz";
        sha512 = "vNk6aEwybGtawWmy/PzwnGDOjCkLWSD2wqvjGGAgOAwCGWySYXfYoxt00IJkTF+8Lb57DwOb3Aa0o9CApepiYQ==";
      };
    };
    "@npmcli/agent-2.2.2" = {
      name = "_at_npmcli_slash_agent";
      packageName = "@npmcli/agent";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@npmcli/agent/-/agent-2.2.2.tgz";
        sha512 = "OrcNPXdpSl9UX7qPVRWbmWMCSXrcDa2M9DvrbOTj7ao1S4PlqVFYv9/yLKMkrJKZ/V5A/kDBC690or307i26Og==";
      };
    };
    "@npmcli/fs-3.1.1" = {
      name = "_at_npmcli_slash_fs";
      packageName = "@npmcli/fs";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@npmcli/fs/-/fs-3.1.1.tgz";
        sha512 = "q9CRWjpHCMIh5sVyefoD1cA7PkvILqCZsnSOEUUivORLjxCO/Irmue2DprETiNgEqktDBZaM1Bi+jrarx1XdCg==";
      };
    };
    "@trysound/sax-0.2.0" = {
      name = "_at_trysound_slash_sax";
      packageName = "@trysound/sax";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@trysound/sax/-/sax-0.2.0.tgz";
        sha512 = "L7z9BgrNEcYyUYtF+HaEfiS5ebkh9jXqbszz7pC0hRBPaatV0XjSD3+eHrpqFemQfgwiFF0QPIarnIihIDn7OA==";
      };
    };
    "@types/node-22.10.7" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "22.10.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-22.10.7.tgz";
        sha512 = "V09KvXxFiutGp6B7XkpaDXlNadZxrzajcY50EuoLIpQ6WWYCSvf19lVIazzfIzQvhUN2HjX12spLojTnhuKlGg==";
      };
    };
    "@types/sax-1.2.7" = {
      name = "_at_types_slash_sax";
      packageName = "@types/sax";
      version = "1.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/sax/-/sax-1.2.7.tgz";
        sha512 = "rO73L89PJxeYM3s3pPPjiPgVVcymqU490g0YO5n5By0k2Erzj6tay/4lr1CHAAU4JyOWd1rpQ8bCf6cZfHU96A==";
      };
    };
    "@types/svg2ttf-5.0.3" = {
      name = "_at_types_slash_svg2ttf";
      packageName = "@types/svg2ttf";
      version = "5.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/svg2ttf/-/svg2ttf-5.0.3.tgz";
        sha512 = "hL+/A4qMISvDbDTtdY73R0zuvsdc7YRYnV5FyAfKVGk8OsluXu/tCFxop7IB5Sgr+ZCS0hHtFxylD0REmm+abA==";
      };
    };
    "@xmldom/xmldom-0.7.13" = {
      name = "_at_xmldom_slash_xmldom";
      packageName = "@xmldom/xmldom";
      version = "0.7.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@xmldom/xmldom/-/xmldom-0.7.13.tgz";
        sha512 = "lm2GW5PkosIzccsaZIz7tp8cPADSIlIHWDFTR1N0SzfinhhYgeIQjFMz4rYzanCScr3DqQLeomUDArp6MWKm+g==";
      };
    };
    "a-sync-waterfall-1.0.1" = {
      name = "a-sync-waterfall";
      packageName = "a-sync-waterfall";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/a-sync-waterfall/-/a-sync-waterfall-1.0.1.tgz";
        sha512 = "RYTOHHdWipFUliRFMCS4X2Yn2X8M87V/OpSqWzKKOGhzqyUxzyVmhHDH9sAvG+ZuQf/TAOFsLCpMw09I1ufUnA==";
      };
    };
    "abbrev-2.0.0" = {
      name = "abbrev";
      packageName = "abbrev";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/abbrev/-/abbrev-2.0.0.tgz";
        sha512 = "6/mh1E2u2YgEsCHdY0Yx5oW+61gZU+1vXaoiHHrpKeuRNNgFvS+/jrwHiQhB5apAf5oB7UB7E19ol2R2LKH8hQ==";
      };
    };
    "acorn-8.14.0" = {
      name = "acorn";
      packageName = "acorn";
      version = "8.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-8.14.0.tgz";
        sha512 = "cl669nCJTZBsL97OF4kUQm5g5hC2uihk0NxY3WENAC0TYdILVkAyHymAntgxGkl7K+t0cXIrH5siy5S4XkFycA==";
      };
    };
    "acorn-jsx-5.3.2" = {
      name = "acorn-jsx";
      packageName = "acorn-jsx";
      version = "5.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn-jsx/-/acorn-jsx-5.3.2.tgz";
        sha512 = "rq9s+JNhf0IChjtDXxllJ7g41oZk5SlXtp0LHwyA5cejwn7vKmKp4pPri6YEePv2PU65sAsegbXtIinmDFDXgQ==";
      };
    };
    "agent-base-7.1.3" = {
      name = "agent-base";
      packageName = "agent-base";
      version = "7.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/agent-base/-/agent-base-7.1.3.tgz";
        sha512 = "jRR5wdylq8CkOe6hei19GGZnxM6rBGwFl3Bg0YItGDimvjGtAvdZk4Pu6Cl4u4Igsws4a1fd1Vq3ezrhn4KmFw==";
      };
    };
    "aggregate-error-3.1.0" = {
      name = "aggregate-error";
      packageName = "aggregate-error";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aggregate-error/-/aggregate-error-3.1.0.tgz";
        sha512 = "4I7Td01quW/RpocfNayFdFVk1qSuoh0E7JrbRJ16nH01HhKFQ88INq9Sd+nd72zqRySlr9BmDA8xlEJ6vJMrYA==";
      };
    };
    "ansi-regex-5.0.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.1.tgz";
        sha512 = "quJQXlTSUGL2LH9SUXo8VwsY4soanhgo6LNSm84E1LBcE8s3O0wpdiRzyR9z/ZZJMlMWv37qOOb9pdJlMUEKFQ==";
      };
    };
    "ansi-regex-6.1.0" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-6.1.0.tgz";
        sha512 = "7HSX4QQb4CspciLpVFwyRe79O3xsIZDDLER21kERQ71oaPodF8jL725AgJMFAYbooIqolJoRLuM81SpeUkpkvA==";
      };
    };
    "ansi-styles-4.3.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
        sha512 = "zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      };
    };
    "ansi-styles-6.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "6.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-6.2.1.tgz";
        sha512 = "bN798gFfQX+viw3R7yrGWRqnrN2oRkEkUjjl4JNn4E8GxxbjtG3FbrEIIY3l8/hrwUwIeCZvi4QuOTP4MErVug==";
      };
    };
    "any-promise-1.3.0" = {
      name = "any-promise";
      packageName = "any-promise";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/any-promise/-/any-promise-1.3.0.tgz";
        sha512 = "7UvmKalWRt1wgjL1RrGxoSJW/0QZFIegpeGvZG9kjp8vrRu55XTHbwnqq2GpXm9uLbcuhxm3IqX9OB4MZR1b2A==";
      };
    };
    "anymatch-3.1.3" = {
      name = "anymatch";
      packageName = "anymatch";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/anymatch/-/anymatch-3.1.3.tgz";
        sha512 = "KMReFUr0B4t+D+OBkjR3KYqvocp2XaSzO55UcB6mgQMd3KbcE+mWTyvVV7D/zsdEbNnV6acZUutkiHQXvTr1Rw==";
      };
    };
    "argparse-2.0.1" = {
      name = "argparse";
      packageName = "argparse";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-2.0.1.tgz";
        sha512 = "8+9WqebbFzpX9OR+Wa6O29asIogeRMzcGtAINdpMHHyAg10f05aSFVBbcEqGf/PXw1EjAZ+q2/bEBg3DvurK3Q==";
      };
    };
    "asap-2.0.6" = {
      name = "asap";
      packageName = "asap";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/asap/-/asap-2.0.6.tgz";
        sha512 = "BSHWgDSAiKs50o2Re8ppvp3seVHXSRM44cdSsT9FfNEUUZLOGWVCsiWaRPWM1Znn+mqZ1OfVZ3z3DWEzSp7hRA==";
      };
    };
    "auto-config-loader-1.7.8" = {
      name = "auto-config-loader";
      packageName = "auto-config-loader";
      version = "1.7.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/auto-config-loader/-/auto-config-loader-1.7.8.tgz";
        sha512 = "mK8yQmJJy369cz0x2LJwhKD72tkTObBwhgR+3U8Ts8+wCSspED3ydXlWpsv1ZQ9g2iq4b+7EWli+ap2nTeUQog==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "binary-extensions-2.3.0" = {
      name = "binary-extensions";
      packageName = "binary-extensions";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/binary-extensions/-/binary-extensions-2.3.0.tgz";
        sha512 = "Ceh+7ox5qe7LJuLHoY0feh3pHuUDHAcRUeyL2VYghZwfpkNIy/+8Ocg0a3UuSoYzavmylwuLWQOf3hl0jjMMIw==";
      };
    };
    "bindings-1.5.0" = {
      name = "bindings";
      packageName = "bindings";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bindings/-/bindings-1.5.0.tgz";
        sha512 = "p2q/t/mhvuOj/UeLlV6566GD/guowlr0hHxClI0W9m7MWYkL1F0hLo+0Aexs9HSPCtR1SXQ0TD3MMKrXZajbiQ==";
      };
    };
    "boolbase-1.0.0" = {
      name = "boolbase";
      packageName = "boolbase";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/boolbase/-/boolbase-1.0.0.tgz";
        sha512 = "JZOSA7Mo9sNGB8+UjSgzdLtokWAky1zbztM3WRLCbZ70/3cTANmQmOdR7y2g+J0e2WXywy1yS468tY+IruqEww==";
      };
    };
    "brace-expansion-2.0.1" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-2.0.1.tgz";
        sha512 = "XnAIvQ8eM+kC6aULx6wuQiwVsnzsi9d3WxzV3FpWTGA19F621kwdbsAcFKXgKUHZWsy+mY6iL1sHTxWEFCytDA==";
      };
    };
    "braces-3.0.3" = {
      name = "braces";
      packageName = "braces";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/braces/-/braces-3.0.3.tgz";
        sha512 = "yQbXgO/OSZVD2IsiLlro+7Hf6Q18EJrKSEsdoMzKePKXct3gvD8oLcOQdIzGupr5Fj+EDe8gO/lxc1BzfMpxvA==";
      };
    };
    "bufferstreams-4.0.0" = {
      name = "bufferstreams";
      packageName = "bufferstreams";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bufferstreams/-/bufferstreams-4.0.0.tgz";
        sha512 = "azX778/2VQ9K2uiYprSUKLgK2K6lR1KtJycJDsMg7u0+Cc994A9HyGaUKb01e/T+M8jse057429iKXurCaT35g==";
      };
    };
    "cacache-18.0.4" = {
      name = "cacache";
      packageName = "cacache";
      version = "18.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/cacache/-/cacache-18.0.4.tgz";
        sha512 = "B+L5iIa9mgcjLbliir2th36yEwPftrzteHYujzsx3dFP/31GCHcIeS8f5MGd80odLOjaOvSpU3EEAmRQptkxLQ==";
      };
    };
    "cheerio-1.0.0" = {
      name = "cheerio";
      packageName = "cheerio";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cheerio/-/cheerio-1.0.0.tgz";
        sha512 = "quS9HgjQpdaXOvsZz82Oz7uxtXiy6UIsIQcpBj7HRw2M63Skasm9qlDocAM7jNuaxdhpPU7c4kJN+gA5MCu4ww==";
      };
    };
    "cheerio-select-2.1.0" = {
      name = "cheerio-select";
      packageName = "cheerio-select";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cheerio-select/-/cheerio-select-2.1.0.tgz";
        sha512 = "9v9kG0LvzrlcungtnJtpGNxY+fzECQKhK4EGJX2vByejiMX84MFNQw4UxPJl3bFbTMw+Dfs37XaIkCwTZfLh4g==";
      };
    };
    "chokidar-3.6.0" = {
      name = "chokidar";
      packageName = "chokidar";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chokidar/-/chokidar-3.6.0.tgz";
        sha512 = "7VT13fmjotKpGipCW9JEQAusEPE+Ei8nl6/g4FBAmIm0GOOLMua9NDDo/DWp0ZAxCr3cPq5ZpBqmPAQgDda2Pw==";
      };
    };
    "chownr-2.0.0" = {
      name = "chownr";
      packageName = "chownr";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chownr/-/chownr-2.0.0.tgz";
        sha512 = "bIomtDF5KGpdogkLd9VspvFzk9KfpyyGlS8YFVZl7TGPBHL5snIOnxeshwVgPteQ9b4Eydl+pVbIyE1DcvCWgQ==";
      };
    };
    "clean-stack-2.2.0" = {
      name = "clean-stack";
      packageName = "clean-stack";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/clean-stack/-/clean-stack-2.2.0.tgz";
        sha512 = "4diC9HaTE+KRAMWhDhrGOECgWZxoevMc5TlkObMqNSsVU62PYzXZ/SMTjzyGAFF1YusgxGcSWTEXBhp0CPwQ1A==";
      };
    };
    "cliui-8.0.1" = {
      name = "cliui";
      packageName = "cliui";
      version = "8.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cliui/-/cliui-8.0.1.tgz";
        sha512 = "BSeNnyus75C4//NQ9gQt1/csTXyo/8Sb+afLAkzAptFuMsod9HFokGNudZpi/oQV73hnVK+sR+5PVRMd+Dr7YQ==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "colors-cli-1.0.33" = {
      name = "colors-cli";
      packageName = "colors-cli";
      version = "1.0.33";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors-cli/-/colors-cli-1.0.33.tgz";
        sha512 = "PWGsmoJFdOB0t+BeHgmtuoRZUQucOLl5ii81NBzOOGVxlgE04muFNHlR5j8i8MKbOPELBl3243AI6lGBTj5ICQ==";
      };
    };
    "commander-12.1.0" = {
      name = "commander";
      packageName = "commander";
      version = "12.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-12.1.0.tgz";
        sha512 = "Vw8qHK3bZM9y/P10u3Vib8o/DdkvA2OtPtZvD871QKjy74Wj1WSKFILMPRPSdUSx5RFK1arlJzEtA4PkFgnbuA==";
      };
    };
    "commander-4.1.1" = {
      name = "commander";
      packageName = "commander";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-4.1.1.tgz";
        sha512 = "NOKm8xhkzAjzFx8B2v5OAHT+u5pRQc2UCa2Vq9jYL/31o2wi9mxBA7LIFs3sV5VSC49z6pEhfbMULvShKj26WA==";
      };
    };
    "commander-5.1.0" = {
      name = "commander";
      packageName = "commander";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-5.1.0.tgz";
        sha512 = "P0CysNDQ7rtVw4QIQtm+MRxV66vKFSvlsQvGYXZWR3qFU0jlMKHZZZgw8e+8DSah4UDKMqnknRDQz+xuQXQ/Zg==";
      };
    };
    "commander-7.2.0" = {
      name = "commander";
      packageName = "commander";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-7.2.0.tgz";
        sha512 = "QrWXB+ZQSVPmIWIhtEO9H+gwHaMGYiF5ChvoJ+K9ZGHG/sVsa6yiesAD1GC/x46sET00Xlwo1u49RVVVzvcSkw==";
      };
    };
    "cross-spawn-7.0.6" = {
      name = "cross-spawn";
      packageName = "cross-spawn";
      version = "7.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.6.tgz";
        sha512 = "uV2QOWP2nWzsy2aMp8aRibhi9dlzF5Hgh5SHaB9OiTGEyDTiJJyx0uy51QXdyWbtAHNua4XJzUKca3OzKUd3vA==";
      };
    };
    "css-select-5.1.0" = {
      name = "css-select";
      packageName = "css-select";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-select/-/css-select-5.1.0.tgz";
        sha512 = "nwoRF1rvRRnnCqqY7updORDsuqKzqYJ28+oSMaJMMgOauh3fvwHqMS7EZpIPqK8GL+g9mKxF1vP/ZjSeNjEVHg==";
      };
    };
    "css-tree-2.2.1" = {
      name = "css-tree";
      packageName = "css-tree";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-tree/-/css-tree-2.2.1.tgz";
        sha512 = "OA0mILzGc1kCOCSJerOeqDxDQ4HOh+G8NbOJFOTgOCzpw7fCBubk0fEyxp8AgOL/jvLgYA/uV0cMbe43ElF1JA==";
      };
    };
    "css-tree-2.3.1" = {
      name = "css-tree";
      packageName = "css-tree";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-tree/-/css-tree-2.3.1.tgz";
        sha512 = "6Fv1DV/TYw//QF5IzQdqsNDjx/wc8TrMBZsqjL9eW01tWb7R7k/mq+/VXfJCl7SoD5emsJop9cOByJZfs8hYIw==";
      };
    };
    "css-what-6.1.0" = {
      name = "css-what";
      packageName = "css-what";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-what/-/css-what-6.1.0.tgz";
        sha512 = "HTUrgRJ7r4dsZKU6GjmpfRK1O76h97Z8MfS1G0FozR+oF2kG6Vfe8JE6zwrkbxigziPHinCJ+gCPjA9EaBDtRw==";
      };
    };
    "csso-5.0.5" = {
      name = "csso";
      packageName = "csso";
      version = "5.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/csso/-/csso-5.0.5.tgz";
        sha512 = "0LrrStPOdJj+SPCCrGhzryycLjwcgUSHBtxNA8aIDxf0GLsRh1cKYhB00Gd1lDOS4yGH69+SNn13+TWbVHETFQ==";
      };
    };
    "cubic2quad-1.2.1" = {
      name = "cubic2quad";
      packageName = "cubic2quad";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cubic2quad/-/cubic2quad-1.2.1.tgz";
        sha512 = "wT5Y7mO8abrV16gnssKdmIhIbA9wSkeMzhh27jAguKrV82i24wER0vL5TGhUJ9dbJNDcigoRZ0IAHFEEEI4THQ==";
      };
    };
    "data-uri-to-buffer-4.0.1" = {
      name = "data-uri-to-buffer";
      packageName = "data-uri-to-buffer";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/data-uri-to-buffer/-/data-uri-to-buffer-4.0.1.tgz";
        sha512 = "0R9ikRb668HB7QDxT1vkpuUBtqc53YyAwMwGeUFKRojY/NWKvdZ+9UYtRfGmhqNbRkTSVpMbmyhXipFFv2cb/A==";
      };
    };
    "debug-4.4.0" = {
      name = "debug";
      packageName = "debug";
      version = "4.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.4.0.tgz";
        sha512 = "6WTZ/IxCY/T6BALoZHaE4ctp9xm+Z5kY/pzYaCHRFeyVhojxlrm+46y68HA6hr0TcwEssoxNiDEUJQjfPZ/RYA==";
      };
    };
    "dom-serializer-2.0.0" = {
      name = "dom-serializer";
      packageName = "dom-serializer";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-serializer/-/dom-serializer-2.0.0.tgz";
        sha512 = "wIkAryiqt/nV5EQKqQpo3SToSOV9J0DnbJqwK7Wv/Trc92zIAYZ4FlMu+JPFW1DfGFt81ZTCGgDEabffXeLyJg==";
      };
    };
    "domelementtype-2.3.0" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-2.3.0.tgz";
        sha512 = "OLETBj6w0OsagBwdXnPdN0cnMfF9opN69co+7ZrbfPGrdpPVNBUj02spi6B1N7wChLQiPn4CSH/zJvXw56gmHw==";
      };
    };
    "domhandler-5.0.3" = {
      name = "domhandler";
      packageName = "domhandler";
      version = "5.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/domhandler/-/domhandler-5.0.3.tgz";
        sha512 = "cgwlv/1iFQiFnU96XXgROh8xTeetsnJiDsTc7TYCLFd9+/WNkIqPTxiM/8pSd8VIrhXGTf1Ny1q1hquVqDJB5w==";
      };
    };
    "domutils-3.2.2" = {
      name = "domutils";
      packageName = "domutils";
      version = "3.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/domutils/-/domutils-3.2.2.tgz";
        sha512 = "6kZKyUajlDuqlHKVX1w7gyslj9MPIXzIFiz/rGu35uC1wMi+kMhQwGhl4lt9unC9Vb9INnY9Z3/ZA3+FhASLaw==";
      };
    };
    "eastasianwidth-0.2.0" = {
      name = "eastasianwidth";
      packageName = "eastasianwidth";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/eastasianwidth/-/eastasianwidth-0.2.0.tgz";
        sha512 = "I88TYZWc9XiYHRQ4/3c5rjjfgkjhLyW2luGIheGERbNQ6OY7yTybanSpDXZa8y7VUP9YmDcYa+eyq4ca7iLqWA==";
      };
    };
    "emoji-regex-8.0.0" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-8.0.0.tgz";
        sha512 = "MSjYzcWNOA0ewAHpz0MxpYFvwg6yjy1NG3xteoqz644VCo/RPgnr1/GGt+ic3iJTzQ8Eu3TdM14SawnVUmGE6A==";
      };
    };
    "emoji-regex-9.2.2" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "9.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-9.2.2.tgz";
        sha512 = "L18DaJsXSUk2+42pv8mLs5jJT2hqFkFE4j21wOmgbUqsZ2hL72NsUU785g9RXgo3s0ZNgVl42TiHp3ZtOv/Vyg==";
      };
    };
    "encoding-sniffer-0.2.0" = {
      name = "encoding-sniffer";
      packageName = "encoding-sniffer";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/encoding-sniffer/-/encoding-sniffer-0.2.0.tgz";
        sha512 = "ju7Wq1kg04I3HtiYIOrUrdfdDvkyO9s5XM8QAj/bN61Yo/Vb4vgJxy5vi4Yxk01gWHbrofpPtpxM8bKger9jhg==";
      };
    };
    "entities-4.5.0" = {
      name = "entities";
      packageName = "entities";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-4.5.0.tgz";
        sha512 = "V0hjH4dGPh9Ao5p0MoRY6BVqtwCjhz6vI5LT8AJ55H+4g9/4vbHx1I54fS0XuclLhDHArPQCiMjDxjaL8fPxhw==";
      };
    };
    "env-paths-2.2.1" = {
      name = "env-paths";
      packageName = "env-paths";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/env-paths/-/env-paths-2.2.1.tgz";
        sha512 = "+h1lkLKhZMTYjog1VEpJNG7NZJWcuc2DDk/qsqSTRRCOXiLjeQ1d1/udrUGhqMxUgAlwKNZ0cf2uqan5GLuS2A==";
      };
    };
    "err-code-2.0.3" = {
      name = "err-code";
      packageName = "err-code";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/err-code/-/err-code-2.0.3.tgz";
        sha512 = "2bmlRpNKBxT/CRmPOlyISQpNj+qSeYvcym/uT0Jx2bMOlKLtSy1ZmLuVxSEKKyor/N5yhvp/ZiG1oE3DEYMSFA==";
      };
    };
    "escalade-3.2.0" = {
      name = "escalade";
      packageName = "escalade";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escalade/-/escalade-3.2.0.tgz";
        sha512 = "WUj2qlxaQtO4g6Pq5c29GTcWGDyd8itL8zTlipgECz3JesAiiOKotd8JU6otB3PACgG6xkJUyVhboMS+bje/jA==";
      };
    };
    "eslint-visitor-keys-3.4.3" = {
      name = "eslint-visitor-keys";
      packageName = "eslint-visitor-keys";
      version = "3.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/eslint-visitor-keys/-/eslint-visitor-keys-3.4.3.tgz";
        sha512 = "wpc+LXeiyiisxPlEkUzU6svyS1frIO3Mgxj1fdy7Pm8Ygzguax2N3Fa/D/ag1WqbOprdI+uY6wMUl8/a2G+iag==";
      };
    };
    "espree-9.6.1" = {
      name = "espree";
      packageName = "espree";
      version = "9.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/espree/-/espree-9.6.1.tgz";
        sha512 = "oruZaFkjorTpF32kDSI5/75ViwGeZginGGy2NoOSg3Q9bnwlnmDm4HLnkl0RE3n+njDXR037aY1+x58Z/zFdwQ==";
      };
    };
    "exponential-backoff-3.1.1" = {
      name = "exponential-backoff";
      packageName = "exponential-backoff";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/exponential-backoff/-/exponential-backoff-3.1.1.tgz";
        sha512 = "dX7e/LHVJ6W3DE1MHWi9S1EYzDESENfLrYohG2G++ovZrYOkm4Knwa0mc1cn84xJOR4KEU0WSchhLbd0UklbHw==";
      };
    };
    "fetch-blob-3.2.0" = {
      name = "fetch-blob";
      packageName = "fetch-blob";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fetch-blob/-/fetch-blob-3.2.0.tgz";
        sha512 = "7yAQpD2UMJzLi1Dqv7qFYnPbaPx7ZfFK6PiIxQ4PfkGPyNyl2Ugx+a/umUonmKqjhM4DnfbMvdX6otXq83soQQ==";
      };
    };
    "file-uri-to-path-1.0.0" = {
      name = "file-uri-to-path";
      packageName = "file-uri-to-path";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-uri-to-path/-/file-uri-to-path-1.0.0.tgz";
        sha512 = "0Zt+s3L7Vf1biwWZ29aARiVYLx7iMGnEUl9x33fbB/j3jR81u/O2LbqK+Bm1CDSNDKVtJ/YjwY7TUd5SkeLQLw==";
      };
    };
    "fill-range-7.1.1" = {
      name = "fill-range";
      packageName = "fill-range";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fill-range/-/fill-range-7.1.1.tgz";
        sha512 = "YsGpe3WHLK8ZYi4tWDg2Jy3ebRz2rXowDxnld4bkQB00cc/1Zw9AWnC0i9ztDJitivtQvaI9KaLyKrc+hBW0yg==";
      };
    };
    "foreground-child-3.3.0" = {
      name = "foreground-child";
      packageName = "foreground-child";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/foreground-child/-/foreground-child-3.3.0.tgz";
        sha512 = "Ld2g8rrAyMYFXBhEqMz8ZAHBi4J4uS1i/CxGMDnjyFWddMXLVcDp051DZfu+t7+ab7Wv6SMqpWmyFIj5UbfFvg==";
      };
    };
    "formdata-polyfill-4.0.10" = {
      name = "formdata-polyfill";
      packageName = "formdata-polyfill";
      version = "4.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/formdata-polyfill/-/formdata-polyfill-4.0.10.tgz";
        sha512 = "buewHzMvYL29jdeQTVILecSaZKnt/RJWjoZCF5OW60Z67/GmSLBkOFM7qh1PI3zFNtJbaZL5eQu1vLfazOwj4g==";
      };
    };
    "fs-extra-11.2.0" = {
      name = "fs-extra";
      packageName = "fs-extra";
      version = "11.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-extra/-/fs-extra-11.2.0.tgz";
        sha512 = "PmDi3uwK5nFuXh7XDTlVnS17xJS7vW36is2+w3xcv8SVxiB4NyATf4ctkVY5bkSjX0Y4nbvZCq1/EjtEyr9ktw==";
      };
    };
    "fs-minipass-2.1.0" = {
      name = "fs-minipass";
      packageName = "fs-minipass";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-minipass/-/fs-minipass-2.1.0.tgz";
        sha512 = "V/JgOLFCS+R6Vcq0slCuaeWEdNC3ouDlJMNIsacH2VtALiu9mV4LPrHc5cDl8k5aw6J8jwgWWpiTo5RYhmIzvg==";
      };
    };
    "fs-minipass-3.0.3" = {
      name = "fs-minipass";
      packageName = "fs-minipass";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-minipass/-/fs-minipass-3.0.3.tgz";
        sha512 = "XUBA9XClHbnJWSfBzjkm6RvPsyg3sryZt06BEQoXcF7EK/xpGaQYJgQKDJSUH5SGZ76Y7pFx1QBnXz09rU5Fbw==";
      };
    };
    "get-caller-file-2.0.5" = {
      name = "get-caller-file";
      packageName = "get-caller-file";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-caller-file/-/get-caller-file-2.0.5.tgz";
        sha512 = "DyFP3BM/3YHTQOCUL/w0OZHR0lpKeGrxotcHWcqNEdnltqFwXVfhEBQ94eIo34AfQpo0rGki4cyIiftY06h2Fg==";
      };
    };
    "glob-10.4.5" = {
      name = "glob";
      packageName = "glob";
      version = "10.4.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-10.4.5.tgz";
        sha512 = "7Bv8RF0k6xjo7d4A/PxYLbUCfb6c+Vpd2/mB2yRDlew7Jb5hEXiCD9ibfO7wpk8i4sevK6DFny9h7EYbM3/sHg==";
      };
    };
    "glob-11.0.1" = {
      name = "glob";
      packageName = "glob";
      version = "11.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-11.0.1.tgz";
        sha512 = "zrQDm8XPnYEKawJScsnM0QzobJxlT/kHOOlRTio8IH/GrmxRE5fjllkzdaHclIuNjUQTJYH2xHNIGfdpJkDJUw==";
      };
    };
    "glob-parent-5.1.2" = {
      name = "glob-parent";
      packageName = "glob-parent";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-parent/-/glob-parent-5.1.2.tgz";
        sha512 = "AOIgSQCepiJYwP3ARnGx+5VnTu2HBYdzbGP45eLw1vr3zB3vZLeyed1sC9hnbcOc9/SrMyM5RPQrkGz4aS9Zow==";
      };
    };
    "graceful-fs-4.2.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.11.tgz";
        sha512 = "RbJ5/jmFcNNCcDV5o9eTnBLJ/HszWV0P73bc+Ff4nS/rJj+YaS6IGyiOL0VoBYX+l1Wrl3k63h/KrH+nhJ0XvQ==";
      };
    };
    "htmlparser2-9.1.0" = {
      name = "htmlparser2";
      packageName = "htmlparser2";
      version = "9.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/htmlparser2/-/htmlparser2-9.1.0.tgz";
        sha512 = "5zfg6mHUoaer/97TxnGpxmbR7zJtPwIYFMZ/H5ucTlPZhKvtum05yiPK3Mgai3a0DyVxv7qYqoweaEd2nrYQzQ==";
      };
    };
    "http-cache-semantics-4.1.1" = {
      name = "http-cache-semantics";
      packageName = "http-cache-semantics";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-cache-semantics/-/http-cache-semantics-4.1.1.tgz";
        sha512 = "er295DKPVsV82j5kw1Gjt+ADA/XYHsajl82cGNQG2eyoPkvgUhX+nDIyelzhIWbbsXP39EHcI6l5tYs2FYqYXQ==";
      };
    };
    "http-proxy-agent-7.0.2" = {
      name = "http-proxy-agent";
      packageName = "http-proxy-agent";
      version = "7.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-proxy-agent/-/http-proxy-agent-7.0.2.tgz";
        sha512 = "T1gkAiYYDWYx3V5Bmyu7HcfcvL7mUrTWiM6yOfa3PIphViJ/gFPbvidQ+veqSOHci/PxBcDabeUNCzpOODJZig==";
      };
    };
    "https-proxy-agent-7.0.6" = {
      name = "https-proxy-agent";
      packageName = "https-proxy-agent";
      version = "7.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/https-proxy-agent/-/https-proxy-agent-7.0.6.tgz";
        sha512 = "vK9P5/iUfdl95AI+JVyUuIcVtd4ofvtrOr3HNtM2yxC9bnMbEdp3x01OhQNnjb8IJYi38VlTE3mBXwcfvywuSw==";
      };
    };
    "iconv-lite-0.6.3" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.6.3.tgz";
        sha512 = "4fCk79wshMdzMp2rH06qWrJE4iolqLhCUH+OiuIgU++RB0+94NlDL81atO7GX55uUKueo0txHNtvEyI6D7WdMw==";
      };
    };
    "image2uri-2.1.2" = {
      name = "image2uri";
      packageName = "image2uri";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/image2uri/-/image2uri-2.1.2.tgz";
        sha512 = "3b2zRma8I3zulb4OCkZruRw1VsnysT9phBzOJj+x3lPkwybJtNa5Sz6Dw8jSQI6OL7Ns4H5h8Y26EJbwq4GhQQ==";
      };
    };
    "imurmurhash-0.1.4" = {
      name = "imurmurhash";
      packageName = "imurmurhash";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/imurmurhash/-/imurmurhash-0.1.4.tgz";
        sha512 = "JmXMZ6wuvDmLiHEml9ykzqO6lwFbof0GG4IkcGaENdCRDDmMVnny7s5HsIgHCbaq0w2MyPhDqkhTUgS2LU2PHA==";
      };
    };
    "indent-string-4.0.0" = {
      name = "indent-string";
      packageName = "indent-string";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/indent-string/-/indent-string-4.0.0.tgz";
        sha512 = "EdDDZu4A2OyIK7Lr/2zG+w5jmbuk1DVBnEwREQvBzspBJkCEbRa8GxU1lghYcaGJCnRWibjDXlq779X1/y5xwg==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "ini-5.0.0" = {
      name = "ini";
      packageName = "ini";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ini/-/ini-5.0.0.tgz";
        sha512 = "+N0ngpO3e7cRUWOJAS7qw0IZIVc6XPrW4MlFBdD066F2L4k1L6ker3hLqSq7iXxU5tgS4WGkIUElWn5vogAEnw==";
      };
    };
    "ip-address-9.0.5" = {
      name = "ip-address";
      packageName = "ip-address";
      version = "9.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/ip-address/-/ip-address-9.0.5.tgz";
        sha512 = "zHtQzGojZXTwZTHQqra+ETKd4Sn3vgi7uBmlPoXVWZqYvuKmtI0l/VZTjqGmJY9x88GGOaZ9+G9ES8hC4T4X8g==";
      };
    };
    "is-binary-path-2.1.0" = {
      name = "is-binary-path";
      packageName = "is-binary-path";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-binary-path/-/is-binary-path-2.1.0.tgz";
        sha512 = "ZMERYes6pDydyuGidse7OsHxtbI7WVeUEozgR/g7rd0xUimYNlvZRE/K2MgZTjWy725IfelLeVcEM97mmtRGXw==";
      };
    };
    "is-extglob-2.1.1" = {
      name = "is-extglob";
      packageName = "is-extglob";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extglob/-/is-extglob-2.1.1.tgz";
        sha512 = "SbKbANkN603Vi4jEZv49LeVJMn4yGwsbzZworEoyEiutsN3nJYdbO36zfhGJ6QEDpOZIFkDtnq5JRxmvl3jsoQ==";
      };
    };
    "is-fullwidth-code-point-3.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz";
        sha512 = "zymm5+u+sCsSWyD9qNaejV3DFvhCKclKdizYaJUuHA83RLjb7nSuGnddCHGv0hk+KY7BMAlsWeK4Ueg6EV6XQg==";
      };
    };
    "is-glob-4.0.3" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-4.0.3.tgz";
        sha512 = "xelSayHH36ZgE7ZWhli7pW34hNbNl8Ojv5KVmkJD4hBdD3th8Tfk9vYasLM+mXWOZhFkgZfxhLSnrwRr4elSSg==";
      };
    };
    "is-lambda-1.0.1" = {
      name = "is-lambda";
      packageName = "is-lambda";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-lambda/-/is-lambda-1.0.1.tgz";
        sha512 = "z7CMFGNrENq5iFB9Bqo64Xk6Y9sg+epq1myIcdHaGnbMTYOxvzsEtdYqQUylB7LxfkvgrrjP32T6Ywciio9UIQ==";
      };
    };
    "is-number-7.0.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-7.0.0.tgz";
        sha512 = "41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha512 = "RHxMLp9lnKHGHRng9QFhRCMbYAcVpn69smSGcq3f36xjgVVWThj4qqLbTLlq7Ssj8B+fIQ1EuCEGI2lKsyQeIw==";
      };
    };
    "isexe-3.1.1" = {
      name = "isexe";
      packageName = "isexe";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-3.1.1.tgz";
        sha512 = "LpB/54B+/2J5hqQ7imZHfdU31OlgQqx7ZicVlkm9kzg9/w8GKLEcFfJl/t7DCEDueOyBAD6zCCwTO6Fzs0NoEQ==";
      };
    };
    "jackspeak-3.4.3" = {
      name = "jackspeak";
      packageName = "jackspeak";
      version = "3.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/jackspeak/-/jackspeak-3.4.3.tgz";
        sha512 = "OGlZQpz2yfahA/Rd1Y8Cd9SIEsqvXkLVoSw/cgwhnhFMDbsQFeZYoJJ7bIZBS9BcamUW96asq/npPWugM+RQBw==";
      };
    };
    "jackspeak-4.0.2" = {
      name = "jackspeak";
      packageName = "jackspeak";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jackspeak/-/jackspeak-4.0.2.tgz";
        sha512 = "bZsjR/iRjl1Nk1UkjGpAzLNfQtzuijhn2g+pbZb98HQ1Gk8vM9hfbxeMBP+M2/UUdwj0RqGG3mlvk2MsAqwvEw==";
      };
    };
    "jiti-1.21.7" = {
      name = "jiti";
      packageName = "jiti";
      version = "1.21.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/jiti/-/jiti-1.21.7.tgz";
        sha512 = "/imKNG4EbWNrVjoNC/1H5/9GFy+tqjGBHCaSsN+P2RnPqjsLmv6UD3Ej+Kj8nBWaRAwyk7kK5ZUc+OEatnTR3A==";
      };
    };
    "jsbn-1.1.0" = {
      name = "jsbn";
      packageName = "jsbn";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbn/-/jsbn-1.1.0.tgz";
        sha512 = "4bYVV3aAMtDTTu4+xsDYa6sy9GyJ69/amsu9sYF2zqjiEoZA5xJi3BrfX3uY+/IekIu7MwdObdbDWpoZdBv3/A==";
      };
    };
    "jsonc-eslint-parser-2.4.0" = {
      name = "jsonc-eslint-parser";
      packageName = "jsonc-eslint-parser";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonc-eslint-parser/-/jsonc-eslint-parser-2.4.0.tgz";
        sha512 = "WYDyuc/uFcGp6YtM2H0uKmUwieOuzeE/5YocFJLnLfclZ4inf3mRn8ZVy1s7Hxji7Jxm6Ss8gqpexD/GlKoGgg==";
      };
    };
    "jsonfile-6.1.0" = {
      name = "jsonfile";
      packageName = "jsonfile";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonfile/-/jsonfile-6.1.0.tgz";
        sha512 = "5dgndWOriYSm5cnYaJNhalLNDKOqFwyDB/rr1E9ZsGciGvKPs8R2xYGCacuf3z6K1YKDz182fd+fY3cn3pMqXQ==";
      };
    };
    "lines-and-columns-1.2.4" = {
      name = "lines-and-columns";
      packageName = "lines-and-columns";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lines-and-columns/-/lines-and-columns-1.2.4.tgz";
        sha512 = "7ylylesZQ/PV29jhEDl3Ufjo6ZX7gCqJr5F7PKrqc93v7fzSymt1BpwEU8nAUXs8qzzvqhbjhK5QZg6Mt/HkBg==";
      };
    };
    "lodash-4.17.21" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
        sha512 = "v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
      };
    };
    "lodash.merge-4.6.2" = {
      name = "lodash.merge";
      packageName = "lodash.merge";
      version = "4.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.merge/-/lodash.merge-4.6.2.tgz";
        sha512 = "0KpjqXRVvrYyCsX1swR/XTK0va6VQkQM6MNo7PqW77ByjAhoARA8EfrP1N4+KlKj8YS0ZUCtRT/YUuhyYDujIQ==";
      };
    };
    "lru-cache-10.4.3" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "10.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-10.4.3.tgz";
        sha512 = "JNAzZcXrCt42VGLuYz0zfAzDfAvJWW6AfYlDBQyDV5DClI2m5sAmK+OIO7s59XfsRsWHp02jAJrRadPRGTt6SQ==";
      };
    };
    "lru-cache-11.0.2" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "11.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-11.0.2.tgz";
        sha512 = "123qHRfJBmo2jXDbo/a5YOQrJoHF/GNQTLzQ5+IdK5pWpceK17yRc6ozlWd25FxvGKQbIUs91fDFkXmDHTKcyA==";
      };
    };
    "make-fetch-happen-13.0.1" = {
      name = "make-fetch-happen";
      packageName = "make-fetch-happen";
      version = "13.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/make-fetch-happen/-/make-fetch-happen-13.0.1.tgz";
        sha512 = "cKTUFc/rbKUd/9meOvgrpJ2WrNzymt6jfRDdwg5UCnVzv9dTpEj9JS5m3wtziXVCjluIXyL8pcaukYqezIzZQA==";
      };
    };
    "mdn-data-2.0.28" = {
      name = "mdn-data";
      packageName = "mdn-data";
      version = "2.0.28";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdn-data/-/mdn-data-2.0.28.tgz";
        sha512 = "aylIc7Z9y4yzHYAJNuESG3hfhC+0Ibp/MAMiaOZgNv4pmEdFyfZhhhny4MNiAfWdBQ1RQ2mfDWmM1x8SvGyp8g==";
      };
    };
    "mdn-data-2.0.30" = {
      name = "mdn-data";
      packageName = "mdn-data";
      version = "2.0.30";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdn-data/-/mdn-data-2.0.30.tgz";
        sha512 = "GaqWWShW4kv/G9IEucWScBx9G1/vsFZZJUO+tD26M8J8z3Kw5RDQjaoZe03YAClgeS/SWPOcb4nkFBTEi5DUEA==";
      };
    };
    "microbuffer-1.0.0" = {
      name = "microbuffer";
      packageName = "microbuffer";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/microbuffer/-/microbuffer-1.0.0.tgz";
        sha512 = "O/SUXauVN4x6RaEJFqSPcXNtLFL+QzJHKZlyDVYFwcDDRVca3Fa/37QXXC+4zAGGa4YhHrHxKXuuHvLDIQECtA==";
      };
    };
    "minimatch-10.0.1" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "10.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-10.0.1.tgz";
        sha512 = "ethXTt3SGGR+95gudmqJ1eNhRO7eGEGIgYA9vnPatK4/etz2MEVDno5GMCibdMTuBMyElzIlgxMna3K94XDIDQ==";
      };
    };
    "minimatch-9.0.5" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "9.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-9.0.5.tgz";
        sha512 = "G6T0ZX48xgozx7587koeX9Ys2NYy6Gmv//P89sEte9V9whIapMNF4idKxnW2QtCcLiTWlb/wfCabAtAFWhhBow==";
      };
    };
    "minipass-3.3.6" = {
      name = "minipass";
      packageName = "minipass";
      version = "3.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/minipass/-/minipass-3.3.6.tgz";
        sha512 = "DxiNidxSEK+tHG6zOIklvNOwm3hvCrbUrdtzY74U6HKTJxvIDfOUL5W5P2Ghd3DTkhhKPYGqeNUIh5qcM4YBfw==";
      };
    };
    "minipass-5.0.0" = {
      name = "minipass";
      packageName = "minipass";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minipass/-/minipass-5.0.0.tgz";
        sha512 = "3FnjYuehv9k6ovOEbyOswadCDPX1piCfhV8ncmYtHOjuPwylVWsghTLo7rabjC3Rx5xD4HDx8Wm1xnMF7S5qFQ==";
      };
    };
    "minipass-7.1.2" = {
      name = "minipass";
      packageName = "minipass";
      version = "7.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/minipass/-/minipass-7.1.2.tgz";
        sha512 = "qOOzS1cBTWYF4BH8fVePDBOO9iptMnGUEZwNc/cMWnTV2nVLZ7VoNWEPHkYczZA0pdoA7dl6e7FL659nX9S2aw==";
      };
    };
    "minipass-collect-2.0.1" = {
      name = "minipass-collect";
      packageName = "minipass-collect";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/minipass-collect/-/minipass-collect-2.0.1.tgz";
        sha512 = "D7V8PO9oaz7PWGLbCACuI1qEOsq7UKfLotx/C0Aet43fCUB/wfQ7DYeq2oR/svFJGYDHPr38SHATeaj/ZoKHKw==";
      };
    };
    "minipass-fetch-3.0.5" = {
      name = "minipass-fetch";
      packageName = "minipass-fetch";
      version = "3.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/minipass-fetch/-/minipass-fetch-3.0.5.tgz";
        sha512 = "2N8elDQAtSnFV0Dk7gt15KHsS0Fyz6CbYZ360h0WTYV1Ty46li3rAXVOQj1THMNLdmrD9Vt5pBPtWtVkpwGBqg==";
      };
    };
    "minipass-flush-1.0.5" = {
      name = "minipass-flush";
      packageName = "minipass-flush";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/minipass-flush/-/minipass-flush-1.0.5.tgz";
        sha512 = "JmQSYYpPUqX5Jyn1mXaRwOda1uQ8HP5KAT/oDSLCzt1BYRhQU0/hDtsB1ufZfEEzMZ9aAVmsBw8+FWsIXlClWw==";
      };
    };
    "minipass-pipeline-1.2.4" = {
      name = "minipass-pipeline";
      packageName = "minipass-pipeline";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minipass-pipeline/-/minipass-pipeline-1.2.4.tgz";
        sha512 = "xuIq7cIOt09RPRJ19gdi4b+RiNvDFYe5JH+ggNvBqGqpQXcru3PcRmOZuHBKWK1Txf9+cQ+HMVN4d6z46LZP7A==";
      };
    };
    "minipass-sized-1.0.3" = {
      name = "minipass-sized";
      packageName = "minipass-sized";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/minipass-sized/-/minipass-sized-1.0.3.tgz";
        sha512 = "MbkQQ2CTiBMlA2Dm/5cY+9SWFEN8pzzOXi6rlM5Xxq0Yqbda5ZQy9sU75a673FE9ZK0Zsbr6Y5iP6u9nktfg2g==";
      };
    };
    "minizlib-2.1.2" = {
      name = "minizlib";
      packageName = "minizlib";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/minizlib/-/minizlib-2.1.2.tgz";
        sha512 = "bAxsR8BVfj60DWXHE3u30oHzfl4G7khkSuPW+qvpd7jFRHm7dLxOjUk1EHACJ/hxLY8phGJ0YhYHZo7jil7Qdg==";
      };
    };
    "mkdirp-1.0.4" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-1.0.4.tgz";
        sha512 = "vVqVZQyf3WLx2Shd0qJ9xuvqgAyKPLAiqITEtqW0oIUjzo3PePDd6fW9iFz30ef7Ysp/oiWqbhszeGWW2T6Gzw==";
      };
    };
    "ms-2.1.3" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.3.tgz";
        sha512 = "6FlzubTLZG3J2a/NVCAleEhjzq5oxgHyaCU9yYXvcLsvoVaHJq/s5xXI6/XXP6tz7R9xAOtHnSO/tXtF3WRTlA==";
      };
    };
    "mz-2.7.0" = {
      name = "mz";
      packageName = "mz";
      version = "2.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mz/-/mz-2.7.0.tgz";
        sha512 = "z81GNO7nnYMEhrGh9LeymoE4+Yr0Wn5McHIZMK5cfQCl+NDX08sCZgUc9/6MHni9IWuFLm1Z3HTCXu2z9fN62Q==";
      };
    };
    "nan-2.22.0" = {
      name = "nan";
      packageName = "nan";
      version = "2.22.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nan/-/nan-2.22.0.tgz";
        sha512 = "nbajikzWTMwsW+eSsNm3QwlOs7het9gGJU5dDZzRTQGk03vyBOauxgI4VakDzE0PtsGTmXPsXTbbjVhRwR5mpw==";
      };
    };
    "negotiator-0.6.4" = {
      name = "negotiator";
      packageName = "negotiator";
      version = "0.6.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/negotiator/-/negotiator-0.6.4.tgz";
        sha512 = "myRT3DiWPHqho5PrJaIRyaMv2kgYf0mUVgBNOYMuCH5Ki1yEiQaf/ZJuQ62nvpc44wL5WDbTX7yGJi1Neevw8w==";
      };
    };
    "node-domexception-1.0.0" = {
      name = "node-domexception";
      packageName = "node-domexception";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-domexception/-/node-domexception-1.0.0.tgz";
        sha512 = "/jKZoMpw0F8GRwl4/eLROPA3cfcXtLApP0QzLmUT/HuPCZWyB7IY9ZrMeKw2O/nFIqPQB3PVM9aYm0F312AXDQ==";
      };
    };
    "node-fetch-3.3.2" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "3.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-3.3.2.tgz";
        sha512 = "dRB78srN/l6gqWulah9SrxeYnxeddIG30+GOqK/9OlLVyLg3HPnr6SqOWTWOXKRwC2eGYCkZ59NNuSgvSrpgOA==";
      };
    };
    "node-gyp-10.3.1" = {
      name = "node-gyp";
      packageName = "node-gyp";
      version = "10.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-gyp/-/node-gyp-10.3.1.tgz";
        sha512 = "Pp3nFHBThHzVtNY7U6JfPjvT/DTE8+o/4xKsLQtBoU+j2HLsGlhcfzflAoUreaJbNmYnX+LlLi0qjV8kpyO6xQ==";
      };
    };
    "nopt-7.2.1" = {
      name = "nopt";
      packageName = "nopt";
      version = "7.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-7.2.1.tgz";
        sha512 = "taM24ViiimT/XntxbPyJQzCG+p4EKOpgD3mxFwW38mGjVUrfERQOeY4EDHjdnptttfHuHQXFx+lTP08Q+mLa/w==";
      };
    };
    "normalize-path-3.0.0" = {
      name = "normalize-path";
      packageName = "normalize-path";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-path/-/normalize-path-3.0.0.tgz";
        sha512 = "6eZs5Ls3WtCisHWp9S2GUy8dqkpGi4BVSz3GaqiE6ezub0512ESztXUwUB6C6IKbQkY2Pnb/mD4WYojCRwcwLA==";
      };
    };
    "nth-check-2.1.1" = {
      name = "nth-check";
      packageName = "nth-check";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/nth-check/-/nth-check-2.1.1.tgz";
        sha512 = "lqjrjmaOoAnWfMmBPL+XNnynZh2+swxiX3WUE0s4yEHI6m+AwrK2UZOimIRl3X/4QctVqS8AiZjFqyOGrMXb/w==";
      };
    };
    "nunjucks-3.2.4" = {
      name = "nunjucks";
      packageName = "nunjucks";
      version = "3.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/nunjucks/-/nunjucks-3.2.4.tgz";
        sha512 = "26XRV6BhkgK0VOxfbU5cQI+ICFUtMLixv1noZn1tGU38kQH5A5nmmbk/O45xdyBhD1esk47nKrY0mvQpZIhRjQ==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha512 = "rJgTQnkUnH1sFw8yT6VSU3zD3sWmu6sZhIseY8VX+GRu3P6F7Fu+JNDoXfklElbLJSnc3FUQHVe4cU5hj+BcUg==";
      };
    };
    "p-map-4.0.0" = {
      name = "p-map";
      packageName = "p-map";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-map/-/p-map-4.0.0.tgz";
        sha512 = "/bjOqmgETBYB5BoEeGVea8dmvHb2m9GLy1E9W43yeyfP6QQCZGFNa+XRceJEuDB6zqr+gKpIAmlLebMpykw/MQ==";
      };
    };
    "package-json-from-dist-1.0.1" = {
      name = "package-json-from-dist";
      packageName = "package-json-from-dist";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/package-json-from-dist/-/package-json-from-dist-1.0.1.tgz";
        sha512 = "UEZIS3/by4OC8vL3P2dTXRETpebLI2NiI5vIrjaD/5UtrkFX/tNbwjTSRAGC/+7CAo2pIcBaRgWmcBBHcsaCIw==";
      };
    };
    "pako-1.0.11" = {
      name = "pako";
      packageName = "pako";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/pako/-/pako-1.0.11.tgz";
        sha512 = "4hLB8Py4zZce5s4yd9XzopqwVv/yGNhV1Bl8NTmCq1763HeK2+EwVTv+leGeL13Dnh2wfbqowVPXCIO0z4taYw==";
      };
    };
    "parse5-7.2.1" = {
      name = "parse5";
      packageName = "parse5";
      version = "7.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse5/-/parse5-7.2.1.tgz";
        sha512 = "BuBYQYlv1ckiPdQi/ohiivi9Sagc9JG+Ozs0r7b/0iK3sKmrb0b9FdWdBbOdx6hBCM/F9Ir82ofnBhtZOjCRPQ==";
      };
    };
    "parse5-htmlparser2-tree-adapter-7.1.0" = {
      name = "parse5-htmlparser2-tree-adapter";
      packageName = "parse5-htmlparser2-tree-adapter";
      version = "7.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse5-htmlparser2-tree-adapter/-/parse5-htmlparser2-tree-adapter-7.1.0.tgz";
        sha512 = "ruw5xyKs6lrpo9x9rCZqZZnIUntICjQAd0Wsmp396Ul9lN/h+ifgVV1x1gZHi8euej6wTfpqX8j+BFQxF0NS/g==";
      };
    };
    "parse5-parser-stream-7.1.2" = {
      name = "parse5-parser-stream";
      packageName = "parse5-parser-stream";
      version = "7.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse5-parser-stream/-/parse5-parser-stream-7.1.2.tgz";
        sha512 = "JyeQc9iwFLn5TbvvqACIF/VXG6abODeB3Fwmv/TGdLk2LfbWkaySGY72at4+Ty7EkPZj854u4CrICqNk2qIbow==";
      };
    };
    "path-key-3.1.1" = {
      name = "path-key";
      packageName = "path-key";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-key/-/path-key-3.1.1.tgz";
        sha512 = "ojmeN0qd+y0jszEtoY48r0Peq5dwMEkIlCOu6Q5f41lfkswXuKtYrhgoTpLnyIcHm24Uhqx+5Tqm2InSwLhE6Q==";
      };
    };
    "path-scurry-1.11.1" = {
      name = "path-scurry";
      packageName = "path-scurry";
      version = "1.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-scurry/-/path-scurry-1.11.1.tgz";
        sha512 = "Xa4Nw17FS9ApQFJ9umLiJS4orGjm7ZzwUrwamcGQuHSzDyth9boKDaycYdDcZDuqYATXw4HFXgaqWTctW/v1HA==";
      };
    };
    "path-scurry-2.0.0" = {
      name = "path-scurry";
      packageName = "path-scurry";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-scurry/-/path-scurry-2.0.0.tgz";
        sha512 = "ypGJsmGtdXUOeM5u93TyeIEfEhM6s+ljAhrk5vAvSx8uyY/02OvrZnA0YNGUrPXfpJMgI1ODd3nwz8Npx4O4cg==";
      };
    };
    "picocolors-1.1.1" = {
      name = "picocolors";
      packageName = "picocolors";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/picocolors/-/picocolors-1.1.1.tgz";
        sha512 = "xceH2snhtb5M9liqDsmEw56le376mTZkEX/jEb/RxNFyegNul7eNslCXP9FDj/Lcu0X8KEyMceP2ntpaHrDEVA==";
      };
    };
    "picomatch-2.3.1" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-2.3.1.tgz";
        sha512 = "JU3teHTNjmE2VCGFzuY8EXzCDVwEqB2a8fsIvwaStHhAWJEeVd1o1QD80CU6+ZdEXXSLbSsuLwJjkCBWqRQUVA==";
      };
    };
    "pirates-4.0.6" = {
      name = "pirates";
      packageName = "pirates";
      version = "4.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/pirates/-/pirates-4.0.6.tgz";
        sha512 = "saLsH7WeYYPiD25LDuLRRY/i+6HaPYr6G1OUlN39otzkSTxKnubR9RTxS3/Kk50s1g2JTgFwWQDQyplC5/SHZg==";
      };
    };
    "proc-log-4.2.0" = {
      name = "proc-log";
      packageName = "proc-log";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/proc-log/-/proc-log-4.2.0.tgz";
        sha512 = "g8+OnU/L2v+wyiVK+D5fA34J7EH8jZ8DDlvwhRCMxmMj7UCBvxiO1mGeN+36JXIKF4zevU4kRBd8lVgG9vLelA==";
      };
    };
    "promise-retry-2.0.1" = {
      name = "promise-retry";
      packageName = "promise-retry";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/promise-retry/-/promise-retry-2.0.1.tgz";
        sha512 = "y+WKFlBR8BGXnsNlIHFGPZmyDf3DFMoLhaflAnyZgV6rG6xu+JwesTo2Q9R6XwYmtmwAFCkAk3e35jEdoeh/3g==";
      };
    };
    "readable-stream-3.6.2" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.2.tgz";
        sha512 = "9u/sniCrY3D5WdsERHzHE4G2YCXqoG5FTHUiCC4SIbr6XcLZBY05ya9EKjYek9O5xOAwjGq+1JdGBAS7Q9ScoA==";
      };
    };
    "readdirp-3.6.0" = {
      name = "readdirp";
      packageName = "readdirp";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readdirp/-/readdirp-3.6.0.tgz";
        sha512 = "hOS089on8RduqdbhvQ5Z37A0ESjsqz6qnRcffsMU3495FuTdqSm+7bhJ29JvIOsBDEEnan5DPu9t3To9VRlMzA==";
      };
    };
    "require-directory-2.1.1" = {
      name = "require-directory";
      packageName = "require-directory";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-directory/-/require-directory-2.1.1.tgz";
        sha512 = "fGxEI7+wsG9xrvdjsrlmL22OMTTiHRwAMroiEeMgq8gzoLC/PQr7RsRDSTLUg/bZAZtF+TVIkHc6/4RIKrui+Q==";
      };
    };
    "retry-0.12.0" = {
      name = "retry";
      packageName = "retry";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/retry/-/retry-0.12.0.tgz";
        sha512 = "9LkiTwjUh6rT555DtE9rTX+BKByPfrMzEAtnlEtdEwr3Nkffwiihqe2bWADg+OQRjt9gl6ICdmB/ZFDCGAtSow==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "sax-1.4.1" = {
      name = "sax";
      packageName = "sax";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sax/-/sax-1.4.1.tgz";
        sha512 = "+aWOz7yVScEGoKNd4PA10LZ8sk0A/z5+nXQG5giUO5rprX9jgYsTdov9qCchZiPIZezbZH+jRut8nPodFAX4Jg==";
      };
    };
    "semver-7.6.3" = {
      name = "semver";
      packageName = "semver";
      version = "7.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.6.3.tgz";
        sha512 = "oVekP1cKtI+CTDvHWYFUcMtsK/00wmAEfyqKfNdARm8u1wNVhSgaX7A8d4UuIlUI5e84iEwOhs7ZPYRmzU9U6A==";
      };
    };
    "shebang-command-2.0.0" = {
      name = "shebang-command";
      packageName = "shebang-command";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-command/-/shebang-command-2.0.0.tgz";
        sha512 = "kHxr2zZpYtdmrN1qDjrrX/Z1rR1kG8Dx+gkpK1G4eXmvXswmcE1hTWBWYUzlraYw1/yZp6YuDY77YtvbN0dmDA==";
      };
    };
    "shebang-regex-3.0.0" = {
      name = "shebang-regex";
      packageName = "shebang-regex";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-3.0.0.tgz";
        sha512 = "7++dFhtcx3353uBaq8DDR4NuxBetBzC7ZQOhmTQInHEd6bSrXdiEyzCvG07Z44UYdLShWUyXt5M/yhz8ekcb1A==";
      };
    };
    "signal-exit-4.1.0" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-4.1.0.tgz";
        sha512 = "bzyZ1e88w9O1iNJbKnOlvYTrWPDl46O1bG0D3XInv+9tkPrxrN8jUUTiFlDkkmKWgn1M6CfIA13SuGqOa9Korw==";
      };
    };
    "smart-buffer-4.2.0" = {
      name = "smart-buffer";
      packageName = "smart-buffer";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/smart-buffer/-/smart-buffer-4.2.0.tgz";
        sha512 = "94hK0Hh8rPqQl2xXc3HsaBoOXKV20MToPkcXvwbISWLEs+64sBq5kFgn2kJDHb1Pry9yrP0dxrCI9RRci7RXKg==";
      };
    };
    "socks-2.8.3" = {
      name = "socks";
      packageName = "socks";
      version = "2.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/socks/-/socks-2.8.3.tgz";
        sha512 = "l5x7VUUWbjVFbafGLxPWkYsHIhEvmF85tbIeFZWc8ZPtoMyybuEhL7Jye/ooC4/d48FgOjSJXgsF/AJPYCW8Zw==";
      };
    };
    "socks-proxy-agent-8.0.5" = {
      name = "socks-proxy-agent";
      packageName = "socks-proxy-agent";
      version = "8.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/socks-proxy-agent/-/socks-proxy-agent-8.0.5.tgz";
        sha512 = "HehCEsotFqbPW9sJ8WVYB6UbmIMv7kUUORIF2Nncq4VQvBfNBLibW9YZR5dlYCSUhwcD628pRllm7n+E+YTzJw==";
      };
    };
    "source-map-js-1.2.1" = {
      name = "source-map-js";
      packageName = "source-map-js";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-js/-/source-map-js-1.2.1.tgz";
        sha512 = "UXWMKhLOwVKb728IUtQPXxfYU+usdybtUrK/8uGE8CQMvrhOpwvzDBwj0QhSL7MQc7vIsISBG8VQ8+IDQxpfQA==";
      };
    };
    "sprintf-js-1.1.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.1.3.tgz";
        sha512 = "Oo+0REFV59/rz3gfJNKQiBlwfHaSESl1pcGyABQsnnIfWOFt6JNj5gCog2U6MLZ//IGYD+nA8nI+mTShREReaA==";
      };
    };
    "ssri-10.0.6" = {
      name = "ssri";
      packageName = "ssri";
      version = "10.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/ssri/-/ssri-10.0.6.tgz";
        sha512 = "MGrFH9Z4NP9Iyhqn16sDtBpRRNJ0Y2hNa6D65h736fVSaPCHr4DM4sWUNvVaSuC+0OBGhwsrydQwmgfg5LncqQ==";
      };
    };
    "string-width-4.2.3" = {
      name = "string-width";
      packageName = "string-width";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-4.2.3.tgz";
        sha512 = "wKyQRQpjJ0sIp62ErSZdGsjMJWsap5oRNihHhu6G7JVO/9jIB6UyevL+tXuOqrng8j/cxKTWyWUwvSTriiZz/g==";
      };
    };
    "string-width-5.1.2" = {
      name = "string-width";
      packageName = "string-width";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-5.1.2.tgz";
        sha512 = "HnLOCR3vjcY8beoNLtcjZ5/nxn2afmME6lhrDrebokqMap+XbeW8n9TXpPDOqdGK5qcI3oT0GKTW6wC7EMiVqA==";
      };
    };
    "string-width-cjs-4.2.3" = {
      name = "string-width-cjs";
      packageName = "string-width-cjs";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-4.2.3.tgz";
        sha512 = "wKyQRQpjJ0sIp62ErSZdGsjMJWsap5oRNihHhu6G7JVO/9jIB6UyevL+tXuOqrng8j/cxKTWyWUwvSTriiZz/g==";
      };
    };
    "string_decoder-1.3.0" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.3.0.tgz";
        sha512 = "hkRX8U1WjJFd8LsDJ2yQ/wWWxaopEsABU1XfkM8A+j0+85JAGppt16cr1Whg6KIbb4okU6Mql6BOj+uup/wKeA==";
      };
    };
    "strip-ansi-6.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz";
        sha512 = "Y38VPSHcqkFrCpFnQ9vuSXmquuv5oXOKpGeT6aGrr3o3Gc9AlVa6JBfUSOCnbxGGZF+/0ooI7KrPuUSztUdU5A==";
      };
    };
    "strip-ansi-7.1.0" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "7.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-7.1.0.tgz";
        sha512 = "iq6eVVI64nQQTRYq2KtEg2d2uU7LElhTJwsH4YzIHZshxlgZms/wIc4VoDQTlG/IvVIrBKG06CrZnp0qv7hkcQ==";
      };
    };
    "strip-ansi-cjs-6.0.1" = {
      name = "strip-ansi-cjs";
      packageName = "strip-ansi-cjs";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz";
        sha512 = "Y38VPSHcqkFrCpFnQ9vuSXmquuv5oXOKpGeT6aGrr3o3Gc9AlVa6JBfUSOCnbxGGZF+/0ooI7KrPuUSztUdU5A==";
      };
    };
    "sucrase-3.35.0" = {
      name = "sucrase";
      packageName = "sucrase";
      version = "3.35.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sucrase/-/sucrase-3.35.0.tgz";
        sha512 = "8EbVDiu9iN/nESwxeSxDKe0dunta1GOlHufmSSXxMD2z2/tMZpDMpvXQGsc+ajGo8y2uYUmixaSRUc/QPoQ0GA==";
      };
    };
    "svg-pathdata-7.1.0" = {
      name = "svg-pathdata";
      packageName = "svg-pathdata";
      version = "7.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/svg-pathdata/-/svg-pathdata-7.1.0.tgz";
        sha512 = "wrvKHXZSYZyODOj5E1l1bMTIo8sR7YCH0E4SA8IgLgMsZq4RypslpYvNSsrdg4ThD6du2KWPyVeKinkqUelGhg==";
      };
    };
    "svg2ttf-6.0.3" = {
      name = "svg2ttf";
      packageName = "svg2ttf";
      version = "6.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/svg2ttf/-/svg2ttf-6.0.3.tgz";
        sha512 = "CgqMyZrbOPpc+WqH7aga4JWkDPso23EgypLsbQ6gN3uoPWwwiLjXvzgrwGADBExvCRJrWFzAeK1bSoSpE7ixSQ==";
      };
    };
    "svgicons2svgfont-15.0.0" = {
      name = "svgicons2svgfont";
      packageName = "svgicons2svgfont";
      version = "15.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/svgicons2svgfont/-/svgicons2svgfont-15.0.0.tgz";
        sha512 = "X5iL08aZJRKwYAGcl6ykQg0T6ce8yGpLdccqMXp6mreObpSdjlME9dRKPFIvFWX9/KTvPFAuYnX1gCaqjw7QUA==";
      };
    };
    "svgo-3.3.2" = {
      name = "svgo";
      packageName = "svgo";
      version = "3.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/svgo/-/svgo-3.3.2.tgz";
        sha512 = "OoohrmuUlBs8B8o6MB2Aevn+pRIH9zDALSR+6hhqVfa6fRwG/Qw9VUMSMW9VNg2CFc/MTIfabtdOVl9ODIJjpw==";
      };
    };
    "svgpath-2.6.0" = {
      name = "svgpath";
      packageName = "svgpath";
      version = "2.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/svgpath/-/svgpath-2.6.0.tgz";
        sha512 = "OIWR6bKzXvdXYyO4DK/UWa1VA1JeKq8E+0ug2DG98Y/vOmMpfZNj+TIG988HjfYSqtcy/hFOtZq/n/j5GSESNg==";
      };
    };
    "tar-6.2.1" = {
      name = "tar";
      packageName = "tar";
      version = "6.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tar/-/tar-6.2.1.tgz";
        sha512 = "DZ4yORTwrbTj/7MZYq2w+/ZFdI6OZ/f9SFHR+71gIVUZhOQPHzVCLpvRnPgyaMpfWxxk/4ONva3GQSyNIKRv6A==";
      };
    };
    "thenify-3.3.1" = {
      name = "thenify";
      packageName = "thenify";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/thenify/-/thenify-3.3.1.tgz";
        sha512 = "RVZSIV5IG10Hk3enotrhvz0T9em6cyHBLkH/YAZuKqd8hRkKhSfCGIcP2KUY0EPxndzANBmNllzWPwak+bheSw==";
      };
    };
    "thenify-all-1.6.0" = {
      name = "thenify-all";
      packageName = "thenify-all";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/thenify-all/-/thenify-all-1.6.0.tgz";
        sha512 = "RNxQH/qI8/t3thXJDwcstUO4zeqo64+Uy/+sNVRBx4Xn2OX+OZ9oP+iJnNFqplFra2ZUVeKCSa2oVWi3T4uVmA==";
      };
    };
    "to-regex-range-5.0.1" = {
      name = "to-regex-range";
      packageName = "to-regex-range";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-regex-range/-/to-regex-range-5.0.1.tgz";
        sha512 = "65P7iz6X5yEr1cwcgvQxbbIw7Uk3gOy5dIdtZ4rDveLqhrdJP+Li/Hx6tyK0NEb+2GCyneCMJiGqrADCSNk8sQ==";
      };
    };
    "toml-eslint-parser-0.10.0" = {
      name = "toml-eslint-parser";
      packageName = "toml-eslint-parser";
      version = "0.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/toml-eslint-parser/-/toml-eslint-parser-0.10.0.tgz";
        sha512 = "khrZo4buq4qVmsGzS5yQjKe/WsFvV8fGfOjDQN0q4iy9FjRfPWRgTFrU8u1R2iu/SfWLhY9WnCi4Jhdrcbtg+g==";
      };
    };
    "transformation-matrix-js-2.7.6" = {
      name = "transformation-matrix-js";
      packageName = "transformation-matrix-js";
      version = "2.7.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/transformation-matrix-js/-/transformation-matrix-js-2.7.6.tgz";
        sha512 = "1CxDIZmCQ3vA0GGnkdMQqxUXVm3xXAFmglPYRS1hr37LzSg22TC7QAWOT38OmdUvMEs/rqcnkFoAsqvzdiluDg==";
      };
    };
    "ts-interface-checker-0.1.13" = {
      name = "ts-interface-checker";
      packageName = "ts-interface-checker";
      version = "0.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/ts-interface-checker/-/ts-interface-checker-0.1.13.tgz";
        sha512 = "Y/arvbn+rrz3JCKl9C4kVNfTfSm2/mEp5FSz5EsZSANGPSlQrpRI5M4PKF+mJnE52jOO90PnPSc3Ur3bTQw0gA==";
      };
    };
    "ttf2eot-3.1.0" = {
      name = "ttf2eot";
      packageName = "ttf2eot";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ttf2eot/-/ttf2eot-3.1.0.tgz";
        sha512 = "aHTbcYosNHVqb2Qtt9Xfta77ae/5y0VfdwNLUS6sGBeGr22cX2JDMo/i5h3uuOf+FAD3akYOr17+fYd5NK8aXw==";
      };
    };
    "ttf2woff-3.0.0" = {
      name = "ttf2woff";
      packageName = "ttf2woff";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ttf2woff/-/ttf2woff-3.0.0.tgz";
        sha512 = "OvmFcj70PhmAsVQKfC15XoKH55cRWuaRzvr2fpTNhTNer6JBpG8n6vOhRrIgxMjcikyYt88xqYXMMVapJ4Rjvg==";
      };
    };
    "ttf2woff2-6.0.1" = {
      name = "ttf2woff2";
      packageName = "ttf2woff2";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ttf2woff2/-/ttf2woff2-6.0.1.tgz";
        sha512 = "QVkHvd4VsJ9cZNnzrfJL4Fhl5tyGkO5ih9PRY3DQ2BicKjyA+92I+00H2p06mBw1d0eCtzSQh5bp7NTUA57trg==";
      };
    };
    "undici-6.21.1" = {
      name = "undici";
      packageName = "undici";
      version = "6.21.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/undici/-/undici-6.21.1.tgz";
        sha512 = "q/1rj5D0/zayJB2FraXdaWxbhWiNKDvu8naDT2dl1yTlvJp4BLtOcp2a5BvgGNQpYYJzau7tf1WgKv3b+7mqpQ==";
      };
    };
    "undici-types-6.20.0" = {
      name = "undici-types";
      packageName = "undici-types";
      version = "6.20.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/undici-types/-/undici-types-6.20.0.tgz";
        sha512 = "Ny6QZ2Nju20vw1SRHe3d9jVu6gJ+4e3+MMpqu7pqE5HT6WsTSlce++GQmK5UXS8mzV8DSYHrQH+Xrf2jVcuKNg==";
      };
    };
    "unique-filename-3.0.0" = {
      name = "unique-filename";
      packageName = "unique-filename";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unique-filename/-/unique-filename-3.0.0.tgz";
        sha512 = "afXhuC55wkAmZ0P18QsVE6kp8JaxrEokN2HGIoIVv2ijHQd419H0+6EigAFcIzXeMIkcIkNBpB3L/DXB3cTS/g==";
      };
    };
    "unique-slug-4.0.0" = {
      name = "unique-slug";
      packageName = "unique-slug";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unique-slug/-/unique-slug-4.0.0.tgz";
        sha512 = "WrcA6AyEfqDX5bWige/4NQfPZMtASNVxdmWR76WESYQVAACSgWcR6e9i0mofqqBxYFtL4oAxPIptY73/0YE1DQ==";
      };
    };
    "universalify-2.0.1" = {
      name = "universalify";
      packageName = "universalify";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/universalify/-/universalify-2.0.1.tgz";
        sha512 = "gptHNQghINnc/vTGIk0SOFGFNXw7JVrlRUtConJRlvaw6DuX0wO5Jeko9sWrMBhh+PsYAZ7oXAiOnf/UKogyiw==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha512 = "EPD5q1uXyFxJpCrLnCc1nHnq3gOa6DZBocAIiI2TaSCA7VCJ1UJDMagCzIkXNsUYfD1daK//LTEQ8xiIbrHtcw==";
      };
    };
    "web-streams-polyfill-3.3.3" = {
      name = "web-streams-polyfill";
      packageName = "web-streams-polyfill";
      version = "3.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/web-streams-polyfill/-/web-streams-polyfill-3.3.3.tgz";
        sha512 = "d2JWLCivmZYTSIoge9MsgFCZrt571BikcWGYkjC1khllbTeDlGqZ2D8vD8E/lJa8WGWbb7Plm8/XJYV7IJHZZw==";
      };
    };
    "whatwg-encoding-3.1.1" = {
      name = "whatwg-encoding";
      packageName = "whatwg-encoding";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/whatwg-encoding/-/whatwg-encoding-3.1.1.tgz";
        sha512 = "6qN4hJdMwfYBtE3YBTTHhoeuUrDBPZmbQaxWAqSALV/MeEnR5z1xd8UKud2RAkFoPkmB+hli1TZSnyi84xz1vQ==";
      };
    };
    "whatwg-mimetype-4.0.0" = {
      name = "whatwg-mimetype";
      packageName = "whatwg-mimetype";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/whatwg-mimetype/-/whatwg-mimetype-4.0.0.tgz";
        sha512 = "QaKxh0eNIi2mE9p2vEdzfagOKHCcj1pJ56EEHGQOVxp8r9/iszLUUV7v89x9O1p/T+NlTM5W7jW6+cz4Fq1YVg==";
      };
    };
    "which-2.0.2" = {
      name = "which";
      packageName = "which";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-2.0.2.tgz";
        sha512 = "BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==";
      };
    };
    "which-4.0.0" = {
      name = "which";
      packageName = "which";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-4.0.0.tgz";
        sha512 = "GlaYyEb07DPxYCKhKzplCWBJtvxZcZMrL+4UkrTSJHHPyZU4mYYTv3qaOe77H7EODLSSopAUFAc6W8U4yqvscg==";
      };
    };
    "wrap-ansi-7.0.0" = {
      name = "wrap-ansi";
      packageName = "wrap-ansi";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-7.0.0.tgz";
        sha512 = "YVGIj2kamLSTxw6NsZjoBxfSwsn0ycdesmc4p+Q21c5zPuZ1pl+NfxVdxPtdHvmNVOQ6XSYG4AUtyt/Fi7D16Q==";
      };
    };
    "wrap-ansi-8.1.0" = {
      name = "wrap-ansi";
      packageName = "wrap-ansi";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-8.1.0.tgz";
        sha512 = "si7QWI6zUMq56bESFvagtmzMdGOtoxfR+Sez11Mobfc7tm+VkUckk9bW2UeffTGVUbOksxmSw0AA2gs8g71NCQ==";
      };
    };
    "wrap-ansi-cjs-7.0.0" = {
      name = "wrap-ansi-cjs";
      packageName = "wrap-ansi-cjs";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-7.0.0.tgz";
        sha512 = "YVGIj2kamLSTxw6NsZjoBxfSwsn0ycdesmc4p+Q21c5zPuZ1pl+NfxVdxPtdHvmNVOQ6XSYG4AUtyt/Fi7D16Q==";
      };
    };
    "y18n-5.0.8" = {
      name = "y18n";
      packageName = "y18n";
      version = "5.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/y18n/-/y18n-5.0.8.tgz";
        sha512 = "0pfFzegeDWJHJIAmTLRP2DwHjdF5s7jo9tuztdQxAhINCdvS+3nGINqPd00AphqJR/0LhANUS6/+7SCb98YOfA==";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
    "yaml-2.7.0" = {
      name = "yaml";
      packageName = "yaml";
      version = "2.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yaml/-/yaml-2.7.0.tgz";
        sha512 = "+hSoy/QHluxmC9kCIJyL/uyFmLmc+e5CFR5Wa+bpIhIj85LVb9ZH2nVnqrHoSvKogwODv0ClqZkmiSSaIH5LTA==";
      };
    };
    "yaml-eslint-parser-1.2.3" = {
      name = "yaml-eslint-parser";
      packageName = "yaml-eslint-parser";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/yaml-eslint-parser/-/yaml-eslint-parser-1.2.3.tgz";
        sha512 = "4wZWvE398hCP7O8n3nXKu/vdq1HcH01ixYlCREaJL5NUMwQ0g3MaGFUBNSlmBtKmhbtVG/Cm6lyYmSVTEVil8A==";
      };
    };
    "yargs-17.7.2" = {
      name = "yargs";
      packageName = "yargs";
      version = "17.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs/-/yargs-17.7.2.tgz";
        sha512 = "7dSzzRQ++CKnNI/krKnYRV7JKKPUXMEh61soaHKg9mrWEhzFWhFnxPxGl+69cD1Ou63C13NUPCnmIcrvqCuM6w==";
      };
    };
    "yargs-parser-21.1.1" = {
      name = "yargs-parser";
      packageName = "yargs-parser";
      version = "21.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs-parser/-/yargs-parser-21.1.1.tgz";
        sha512 = "tVpsJW7DdjecAiFpbIB1e3qxIQsE6NoPc5/eTdrbbIC4h0LVsWhnoa3g+m2HclBIujHzsxZ4VJVA+GUuc2/LBw==";
      };
    };
    "yerror-8.0.0" = {
      name = "yerror";
      packageName = "yerror";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yerror/-/yerror-8.0.0.tgz";
        sha512 = "FemWD5/UqNm8ffj8oZIbjWXIF2KE0mZssggYpdaQkWDDgXBQ/35PNIxEuz6/YLn9o0kOxDBNJe8x8k9ljD7k/g==";
      };
    };
  };
in
{
  svgtofont = nodeEnv.buildNodePackage {
    name = "svgtofont";
    packageName = "svgtofont";
    version = "6.2.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/svgtofont/-/svgtofont-6.2.0.tgz";
      sha512 = "aIYTVfQyzVAOMbUYxXbAyERP56rSrNzbVPE1TcP+RA5WHVby7Seo9YT4hl3zT7krwQ/WXU7OiLLPt0rvxD9mIQ==";
    };
    dependencies = [
      sources."@isaacs/cliui-8.0.2"
      sources."@jridgewell/gen-mapping-0.3.8"
      sources."@jridgewell/resolve-uri-3.1.2"
      sources."@jridgewell/set-array-1.2.1"
      sources."@jridgewell/sourcemap-codec-1.5.0"
      sources."@jridgewell/trace-mapping-0.3.25"
      sources."@npmcli/agent-2.2.2"
      sources."@npmcli/fs-3.1.1"
      sources."@trysound/sax-0.2.0"
      sources."@types/node-22.10.7"
      sources."@types/sax-1.2.7"
      sources."@types/svg2ttf-5.0.3"
      sources."@xmldom/xmldom-0.7.13"
      sources."a-sync-waterfall-1.0.1"
      sources."abbrev-2.0.0"
      sources."acorn-8.14.0"
      sources."acorn-jsx-5.3.2"
      sources."agent-base-7.1.3"
      sources."aggregate-error-3.1.0"
      sources."ansi-regex-5.0.1"
      sources."ansi-styles-6.2.1"
      sources."any-promise-1.3.0"
      sources."anymatch-3.1.3"
      sources."argparse-2.0.1"
      sources."asap-2.0.6"
      sources."auto-config-loader-1.7.8"
      sources."balanced-match-1.0.2"
      sources."binary-extensions-2.3.0"
      sources."bindings-1.5.0"
      sources."boolbase-1.0.0"
      sources."brace-expansion-2.0.1"
      sources."braces-3.0.3"
      sources."bufferstreams-4.0.0"
      (
        sources."cacache-18.0.4"
        // {
          dependencies = [
            sources."fs-minipass-3.0.3"
          ];
        }
      )
      sources."cheerio-1.0.0"
      sources."cheerio-select-2.1.0"
      sources."chokidar-3.6.0"
      sources."chownr-2.0.0"
      sources."clean-stack-2.2.0"
      (
        sources."cliui-8.0.1"
        // {
          dependencies = [
            sources."ansi-styles-4.3.0"
            sources."emoji-regex-8.0.0"
            sources."string-width-4.2.3"
            sources."strip-ansi-6.0.1"
            sources."wrap-ansi-7.0.0"
          ];
        }
      )
      sources."color-convert-2.0.1"
      sources."color-name-1.1.4"
      sources."colors-cli-1.0.33"
      sources."commander-4.1.1"
      sources."cross-spawn-7.0.6"
      sources."css-select-5.1.0"
      (
        sources."css-tree-2.3.1"
        // {
          dependencies = [
            sources."mdn-data-2.0.30"
          ];
        }
      )
      sources."css-what-6.1.0"
      (
        sources."csso-5.0.5"
        // {
          dependencies = [
            sources."css-tree-2.2.1"
          ];
        }
      )
      sources."cubic2quad-1.2.1"
      sources."data-uri-to-buffer-4.0.1"
      sources."debug-4.4.0"
      sources."dom-serializer-2.0.0"
      sources."domelementtype-2.3.0"
      sources."domhandler-5.0.3"
      sources."domutils-3.2.2"
      sources."eastasianwidth-0.2.0"
      sources."emoji-regex-9.2.2"
      sources."encoding-sniffer-0.2.0"
      sources."entities-4.5.0"
      sources."env-paths-2.2.1"
      sources."err-code-2.0.3"
      sources."escalade-3.2.0"
      sources."eslint-visitor-keys-3.4.3"
      sources."espree-9.6.1"
      sources."exponential-backoff-3.1.1"
      sources."fetch-blob-3.2.0"
      sources."file-uri-to-path-1.0.0"
      sources."fill-range-7.1.1"
      sources."foreground-child-3.3.0"
      sources."formdata-polyfill-4.0.10"
      sources."fs-extra-11.2.0"
      (
        sources."fs-minipass-2.1.0"
        // {
          dependencies = [
            sources."minipass-3.3.6"
          ];
        }
      )
      sources."get-caller-file-2.0.5"
      sources."glob-10.4.5"
      sources."glob-parent-5.1.2"
      sources."graceful-fs-4.2.11"
      sources."htmlparser2-9.1.0"
      sources."http-cache-semantics-4.1.1"
      sources."http-proxy-agent-7.0.2"
      sources."https-proxy-agent-7.0.6"
      sources."iconv-lite-0.6.3"
      sources."image2uri-2.1.2"
      sources."imurmurhash-0.1.4"
      sources."indent-string-4.0.0"
      sources."inherits-2.0.4"
      sources."ini-5.0.0"
      sources."ip-address-9.0.5"
      sources."is-binary-path-2.1.0"
      sources."is-extglob-2.1.1"
      sources."is-fullwidth-code-point-3.0.0"
      sources."is-glob-4.0.3"
      sources."is-lambda-1.0.1"
      sources."is-number-7.0.0"
      sources."isexe-2.0.0"
      sources."jackspeak-3.4.3"
      sources."jiti-1.21.7"
      sources."jsbn-1.1.0"
      sources."jsonc-eslint-parser-2.4.0"
      sources."jsonfile-6.1.0"
      sources."lines-and-columns-1.2.4"
      sources."lodash-4.17.21"
      sources."lodash.merge-4.6.2"
      sources."lru-cache-10.4.3"
      sources."make-fetch-happen-13.0.1"
      sources."mdn-data-2.0.28"
      sources."microbuffer-1.0.0"
      sources."minimatch-9.0.5"
      sources."minipass-7.1.2"
      sources."minipass-collect-2.0.1"
      sources."minipass-fetch-3.0.5"
      (
        sources."minipass-flush-1.0.5"
        // {
          dependencies = [
            sources."minipass-3.3.6"
          ];
        }
      )
      (
        sources."minipass-pipeline-1.2.4"
        // {
          dependencies = [
            sources."minipass-3.3.6"
          ];
        }
      )
      (
        sources."minipass-sized-1.0.3"
        // {
          dependencies = [
            sources."minipass-3.3.6"
          ];
        }
      )
      (
        sources."minizlib-2.1.2"
        // {
          dependencies = [
            sources."minipass-3.3.6"
          ];
        }
      )
      sources."mkdirp-1.0.4"
      sources."ms-2.1.3"
      sources."mz-2.7.0"
      sources."nan-2.22.0"
      sources."negotiator-0.6.4"
      sources."node-domexception-1.0.0"
      sources."node-fetch-3.3.2"
      (
        sources."node-gyp-10.3.1"
        // {
          dependencies = [
            sources."isexe-3.1.1"
            sources."which-4.0.0"
          ];
        }
      )
      sources."nopt-7.2.1"
      sources."normalize-path-3.0.0"
      sources."nth-check-2.1.1"
      (
        sources."nunjucks-3.2.4"
        // {
          dependencies = [
            sources."commander-5.1.0"
          ];
        }
      )
      sources."object-assign-4.1.1"
      sources."p-map-4.0.0"
      sources."package-json-from-dist-1.0.1"
      sources."pako-1.0.11"
      sources."parse5-7.2.1"
      sources."parse5-htmlparser2-tree-adapter-7.1.0"
      sources."parse5-parser-stream-7.1.2"
      sources."path-key-3.1.1"
      sources."path-scurry-1.11.1"
      sources."picocolors-1.1.1"
      sources."picomatch-2.3.1"
      sources."pirates-4.0.6"
      sources."proc-log-4.2.0"
      sources."promise-retry-2.0.1"
      sources."readable-stream-3.6.2"
      sources."readdirp-3.6.0"
      sources."require-directory-2.1.1"
      sources."retry-0.12.0"
      sources."safe-buffer-5.2.1"
      sources."safer-buffer-2.1.2"
      sources."sax-1.4.1"
      sources."semver-7.6.3"
      sources."shebang-command-2.0.0"
      sources."shebang-regex-3.0.0"
      sources."signal-exit-4.1.0"
      sources."smart-buffer-4.2.0"
      sources."socks-2.8.3"
      sources."socks-proxy-agent-8.0.5"
      sources."source-map-js-1.2.1"
      sources."sprintf-js-1.1.3"
      sources."ssri-10.0.6"
      sources."string-width-5.1.2"
      (
        sources."string-width-cjs-4.2.3"
        // {
          dependencies = [
            sources."emoji-regex-8.0.0"
            sources."strip-ansi-6.0.1"
          ];
        }
      )
      sources."string_decoder-1.3.0"
      (
        sources."strip-ansi-7.1.0"
        // {
          dependencies = [
            sources."ansi-regex-6.1.0"
          ];
        }
      )
      sources."strip-ansi-cjs-6.0.1"
      sources."sucrase-3.35.0"
      sources."svg-pathdata-7.1.0"
      sources."svg2ttf-6.0.3"
      (
        sources."svgicons2svgfont-15.0.0"
        // {
          dependencies = [
            sources."commander-12.1.0"
            sources."glob-11.0.1"
            sources."jackspeak-4.0.2"
            sources."lru-cache-11.0.2"
            sources."minimatch-10.0.1"
            sources."path-scurry-2.0.0"
          ];
        }
      )
      (
        sources."svgo-3.3.2"
        // {
          dependencies = [
            sources."commander-7.2.0"
          ];
        }
      )
      sources."svgpath-2.6.0"
      (
        sources."tar-6.2.1"
        // {
          dependencies = [
            sources."minipass-5.0.0"
          ];
        }
      )
      sources."thenify-3.3.1"
      sources."thenify-all-1.6.0"
      sources."to-regex-range-5.0.1"
      sources."toml-eslint-parser-0.10.0"
      sources."transformation-matrix-js-2.7.6"
      sources."ts-interface-checker-0.1.13"
      sources."ttf2eot-3.1.0"
      sources."ttf2woff-3.0.0"
      sources."ttf2woff2-6.0.1"
      sources."undici-6.21.1"
      sources."undici-types-6.20.0"
      sources."unique-filename-3.0.0"
      sources."unique-slug-4.0.0"
      sources."universalify-2.0.1"
      sources."util-deprecate-1.0.2"
      sources."web-streams-polyfill-3.3.3"
      sources."whatwg-encoding-3.1.1"
      sources."whatwg-mimetype-4.0.0"
      sources."which-2.0.2"
      sources."wrap-ansi-8.1.0"
      (
        sources."wrap-ansi-cjs-7.0.0"
        // {
          dependencies = [
            sources."ansi-styles-4.3.0"
            sources."emoji-regex-8.0.0"
            sources."string-width-4.2.3"
            sources."strip-ansi-6.0.1"
          ];
        }
      )
      sources."y18n-5.0.8"
      sources."yallist-4.0.0"
      sources."yaml-2.7.0"
      sources."yaml-eslint-parser-1.2.3"
      (
        sources."yargs-17.7.2"
        // {
          dependencies = [
            sources."emoji-regex-8.0.0"
            sources."string-width-4.2.3"
            sources."strip-ansi-6.0.1"
          ];
        }
      )
      sources."yargs-parser-21.1.1"
      sources."yerror-8.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Converts SVG to TTF/EOT/WOFF/WOFF2/SVG format fonts.";
      homepage = "https://jaywcjlove.github.io/svgtofont/";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
