name: update-flake-locks
on:
  workflow_dispatch: # allows manual triggers
  schedule:
    - cron: "0 0 * * 0" # runs weekly on Sunday at midnight

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

jobs:
  lockfile-root:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9

      - name: Update root flake.lock
        uses: DeterminateSystems/update-flake-lock@v20
        with:
          token: ${{ secrets.GH_TOKEN }}
          pr-title: "chore: update root flake.lock dependencies"
          pr-labels: |
            dependencies
            automated
          commit-msg: "chore: update root flake.lock dependencies"
          branch: "auto-update/root-flake"

  lockfile-nixvim:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9

      - name: Update nixvim flake.lock
        uses: DeterminateSystems/update-flake-lock@v20
        with:
          token: ${{ secrets.GH_TOKEN }}
          path: ./nixvim
          pr-title: "chore: update nixvim flake.lock dependencies"
          pr-labels: |
            dependencies
            automated
          commit-msg: "chore: update nixvim flake.lock dependencies"
          branch: "auto-update/nixvim-flake"
