name: update-flake-locks
on:
  workflow_dispatch: # allows manual triggers
  schedule:
    - cron: '0 0 * * 0' # runs weekly on Sunday at midnight

jobs:
  lockfile-root:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Update root flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "fix: update root flake.lock"
          pr-labels: |
            dependencies
            automated

  lockfile-nixvim:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Update nixvim flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          path: nixvim
          pr-title: "fix: update nixvim flake.lock"
          pr-labels: |
            dependencies
            automated
